import { useApp } from '../context/AppContext'
import { TrendingUp, Users, CheckCircle, AlertTriangle } from 'lucide-react'

const fmt = n => `KES ${Number(n).toLocaleString()}`

export default function ReportsPage() {
  const { loans } = useApp()

  const total = loans.reduce((s,l) => s+Number(l.amount), 0)
  const approved = loans.filter(l=>l.status==='approved')
  const byOcc = loans.reduce((acc,l) => { acc[l.occ]=(acc[l.occ]||0)+1; return acc }, {})
  const byCounty = loans.reduce((acc,l) => { acc[l.county]=(acc[l.county]||0)+1; return acc }, {})

  const sorted = Object.entries(byOcc).sort((a,b)=>b[1]-a[1]).slice(0,6)
  const maxOcc = Math.max(...sorted.map(e=>e[1]))

  return (
    <div className="page-wrap fade-in">
      <div style={{ marginBottom:32 }}>
        <h1 className="page-title">Reports & Analytics</h1>
        <p className="page-subtitle">Portfolio overview · January 2025</p>
      </div>

      <div className="metric-grid" style={{ marginBottom:32 }}>
        <div className="metric-card gold">
          <div className="metric-label">Portfolio Value</div>
          <div className="metric-value">{fmt(total)}</div>
          <div className="metric-sub"><span className="metric-trend up"><TrendingUp size={12}/> +12% MoM</span></div>
        </div>
        <div className="metric-card forest">
          <div className="metric-label">Approval Rate</div>
          <div className="metric-value">{Math.round((approved.length/loans.length)*100)}%</div>
          <div className="metric-sub">{approved.length} of {loans.length} applications</div>
        </div>
        <div className="metric-card earth">
          <div className="metric-label">Avg Loan Size</div>
          <div className="metric-value">KES {Math.round(total/loans.length/1000)}K</div>
          <div className="metric-sub">Across all applications</div>
        </div>
        <div className="metric-card info">
          <div className="metric-label">AI Coverage</div>
          <div className="metric-value">{Math.round((loans.filter(l=>l.agentRun).length/loans.length)*100)}%</div>
          <div className="metric-sub">Agent-triaged this month</div>
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:24, marginBottom:24 }}>
        {/* By occupation */}
        <div className="card card-pad">
          <h2 className="section-head">By Occupation</h2>
          <div style={{ display:'flex', flexDirection:'column', gap:12 }}>
            {sorted.map(([occ,count]) => (
              <div key={occ}>
                <div style={{ display:'flex', justifyContent:'space-between', marginBottom:5 }}>
                  <span style={{ fontSize:'0.84rem', fontWeight:600 }}>{occ}</span>
                  <span style={{ fontFamily:'var(--ff-mono)', fontSize:'0.8rem', color:'var(--ink-mute)' }}>{count}</span>
                </div>
                <div className="progress-bar">
                  <div className="progress-fill green" style={{ width:`${(count/maxOcc)*100}%` }}/>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* By county */}
        <div className="card card-pad">
          <h2 className="section-head">By County</h2>
          <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
            {Object.entries(byCounty).sort((a,b)=>b[1]-a[1]).map(([county,count]) => (
              <div key={county} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'8px 0', borderBottom:'1px solid var(--paper-warm)' }}>
                <span style={{ fontSize:'0.88rem', fontWeight:600 }}>{county}</span>
                <div style={{ display:'flex', alignItems:'center', gap:10 }}>
                  {county==='Busia' && <span className="badge badge-earth"><AlertTriangle size={10}/> Monitored</span>}
                  <span className="badge badge-mute">{count} loan{count>1?'s':''}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* SDG Impact */}
      <div className="card card-pad" style={{ background:'var(--forest)', borderColor:'transparent' }}>
        <h2 style={{ fontFamily:'var(--ff-display)', fontSize:'1.2rem', color:'var(--white)', marginBottom:20 }}>SDG Impact Dashboard</h2>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:16 }}>
          {[
            { sdg:'SDG 1', icon:'🏠', label:'No Poverty', value:'68%', desc:'of borrowers below poverty line' },
            { sdg:'SDG 5', icon:'👩', label:'Gender Equality', value:'72%', desc:'female borrowers this month' },
            { sdg:'SDG 8', icon:'💼', label:'Decent Work', value:'KES 283K', desc:'income generated by borrowers' },
            { sdg:'SDG 10', icon:'⚖️', label:'Reduced Inequality', value:'37%', desc:'projected increase for informal traders' },
          ].map(s => (
            <div key={s.sdg} style={{ background:'rgba(255,255,255,.07)', borderRadius:'var(--r-md)', padding:16, textAlign:'center' }}>
              <div style={{ fontSize:'1.5rem', marginBottom:6 }}>{s.icon}</div>
              <div style={{ fontSize:'0.65rem', fontWeight:700, color:'var(--gold)', textTransform:'uppercase', letterSpacing:'0.07em', marginBottom:4 }}>{s.sdg}</div>
              <div style={{ fontFamily:'var(--ff-display)', fontSize:'1.3rem', fontWeight:700, color:'var(--white)', marginBottom:3 }}>{s.value}</div>
              <div style={{ fontSize:'0.72rem', color:'rgba(255,255,255,.55)', lineHeight:1.4 }}>{s.desc}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
